project:
  type: book
  output-dir: docs
  
book:
  title: "Instrumental Phonetics"
  author: "Г. А. Мороз"
  repo-url: https://github.com/agricolamz/2024_HSE_m_instrumental_phonetics
  chapters:
    - index.qmd
    - 01-introduction-to-acoustic-phonetics.qmd
    - 02-bioacoustics.qmd
    - 03-vowels.qmd

callout-appearance: simple
callout-icon: false
bibliography: bibliography.bib

format:
  html:
    theme: cosmo
